[project]
name = 'Secure-Document-Notarization'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.document-hash]
path = 'contracts/document-hash.clar'
clarity_version = 2
epoch = 2.5

[contracts.notary-verification]
path = 'contracts/notary-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
